/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.java.receive;

public class App {
    public static void main(String[] args) {
        while (true) {
            sqsReceiver.receiver();
        }
    }
}
