/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.java.send;


public class App {

    public static void main(String[] args) {
        for (int i=0; i<30; i++) {
            sqsSender.sender(i);
        }
    }
}
